### ISSUE TITLE
New config structure

### ISSUE THREAD

**Issue by vlamug** [vlamug/datpler#5]
Proposal config structure:

```yaml
# inputs for receiving or scraping data
inputs:
 - name: some_input_via_api
    type: API|syslog|client
    listenAddr: ...
    otherAdditionalFields...

# to parse data by specific template
templates:
 - name: text_separated_via_splitter
    type: splitter
    splitter: "|"
    otherAdditionalFields...

# outputs for exposing metrics or sending them somewhere
outpus:
 - name: prometheus_expooose
    listenAddr: 9090
    path: /metrics
    otherAdditionalFields...

# section for metrics
metrics:
 - name: some_grouped_metrics
    rules:
     - name: some_metrics
       otherAdditionalFields...

# stream define the flow of data(the getting data, parsing, evaluating metrics and expose them)
streams:
 - name: some_stream_name
    input: input_name
    template: template_name
    metrics: metric_group_name
    output: outputs
```
